### ISSUE TITLE
Unhandled exception after connecting iPhone

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MziRintu/iphonebrowser#102]
```
What steps will reproduce the problem?
1. Downloaded and installed 1.9.1.0
2. Started it from windows start on Vista.
3. Connected iPhone to the computer
4. it showed it connected, but any time I clicked anywhere, it showed Not 
Responding in the top bar.
5. Error message showed up.

What is the expected output? What do you see instead?
Instead of it working, I got an error message, with the following details:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Path does not exist
   at Manzana.iPhone.GetFiles(String path)
   at iPhoneBrowser.frmMain.loadFiles()
   at iPhoneBrowser.frmMain.trvFolders_AfterSelect(Object sender, 
TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& 
m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, 
IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3074 (QFE.050727-3000)
    CodeBase: 
file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
iPhoneBrowser
    Assembly Version: 1.9.1.0
    Win32 Version: 1.9.1.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/iPhoneBrowser.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7
f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/Syste
m.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c56
1934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a
3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f
11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3074 (QFE.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/S
ystem.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5
c561934e089/System.Runtime.Remoting.dll
----------------------------------------
AxInterop.QTOControlLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: 
file:///C:/Program%20Files/iPhoneBrowser/AxInterop.QTOControlLib.DLL
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/Windows/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3
a/Accessibility.dll
----------------------------------------
Interop.QTOControlLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: 
file:///C:/Program%20Files/iPhoneBrowser/Interop.QTOControlLib.DLL
----------------------------------------
Interop.QTOLibrary
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: 
file:///C:/Program%20Files/iPhoneBrowser/Interop.QTOLibrary.DLL
----------------------------------------
Manzana
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/Manzana.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.




What version of the product are you using? On what operating system?
1.9.1.0 on Vista Ultimate SP1


Please provide any additional information below.
The error message pop-up has a title bar: Microsoft .NET Framework
and the message above the details is: Unhandled exception has occurred in 
your application. If you click Continue, the application will ignore this 
error and attempt to continue. If you click Quit, the application will 
close immediately. 
Path does not exist.


```

Original issue reported on code.google.com by `posa...@gmail.com` on 18 Jun 2009 at 10:10

**Comment by GoogleCodeExporter** [comment]
```
Can you post a screenshot before you click and exactly what you clicked on?
```

Original comment by `NetMage....@gmail.com` on 18 Jun 2009 at 11:20
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem.  Without the iphone connected, the program starts 
fine. 
Then when the ipod is connected, the program crashes.  It happens with itunes 
open
AND with itunes not opened.  If the iphone is connected when the program is 
opened,
the program crashes on startup.

I am running the program on vista 32bit sp2.  I have tried running it as
administrator.  My iphone is a 3gs running 3.1 (out of box 3.1, not 
jailbroken). 
itunes 9.0.1.8
```

Original comment by `andrewjs...@gmail.com` on 11 Oct 2009 at 2:54

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I have the same Problem with vs. 1.8.1 and 1.9.1

I also tried with installing afc2add from cydia, no chance.

My config:

- Windows 7 professional
- iTunes 9.0.1.8 (opened)
- Iphone 3G with OS v3.1.2 (jailbraked with Pwnage under MacOS)

Here the screenshots. Just started the prog and connected Iphone.


```

Original comment by `dart...@gmail.com` on 17 Oct 2009 at 1:52

Attachments:
- [Screenshot 1.8.1.png](https://storage.googleapis.com/google-code-attachments/iphonebrowser/issue-102/comment-6/Screenshot 1.8.1.png)
- [Screenshot 1.9.1.png](https://storage.googleapis.com/google-code-attachments/iphonebrowser/issue-102/comment-6/Screenshot 1.9.1.png)

**Comment by GoogleCodeExporter** [comment]
```
This is identical to Issue #140.

With v1.9.3 Beta, the problem is solved to me.

- dartrax
```

Original comment by `dart...@gmail.com` on 17 Oct 2009 at 2:00

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I encountered the same problem with vs.1.9.1

My config:

- Windows 7 professional
- iTunes 9.0.1.8
- Iphone 3G with OS v3.1.2 unjailbraked

After being tried several times in vain, I searched another program named 
Wondershare
iPhone Transfer ( available free on http://www.itoolkit-software.com ) which is 
able
to handle inter-transferring of music/video/photo/contacts/SMS files between 
iPhone
and iTunes & PC.

Anyone has the same problem without solution can take it as an alternative.


```

Original comment by `alexzong8@gmail.com` on 25 Feb 2010 at 7:34

Attachments:
- [iPhone-Toolkit.jpg](https://storage.googleapis.com/google-code-attachments/iphonebrowser/issue-102/comment-9/iPhone-Toolkit.jpg)
