### ISSUE TITLE
iPhoneBrowser 1.9.1.0 fails with 3.0 and 8.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MziRintu/iphonebrowser#104]
```
What steps will reproduce the problem?
1. Update to iTunes 8.2 and iPhone FW 3.0
2. Start iPhoneBrowser 1.9.1.0
3. Read Errors

What is the expected output? What do you see instead?
iPhoneBrowser should run, crashes with following:

Unable to find an entry point named 'AFCGetFileInfo' in DLL
'iTunesMobileDevice.dll'

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.EntryPointNotFoundException: Unable to find an entry point named
'AFCGetFileInfo' in DLL 'iTunesMobileDevice.dll'.
   at Manzana.MobileDevice.AFCGetFileInfo(IntPtr conn, String path, IntPtr&
buffer, UInt32& length)
   at Manzana.iPhone.GetFileInfo(String path, UInt64& size, Boolean& directory)
   at Manzana.iPhone.GetFiles(String path)
   at iPhoneBrowser.frmMain.loadFiles()
   at iPhoneBrowser.frmMain.trvFolders_AfterSelect(Object sender,
TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3082 (QFE.050727-3000)
    CodeBase:
file:///C:/WINDOWS/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------

What version of the product are you using? On what operating system?
1.9.1.0 Windows XP SP3

Please provide any additional information below.


```

Original issue reported on code.google.com by `todd...@gmail.com` on 20 Jun 2009 at 2:02

**Comment by GoogleCodeExporter** [comment]
```
Please search your computer and make sure you don't have older or other copies 
of
iTunesMobile.dll.
```

Original comment by `NetMage....@gmail.com` on 20 Jun 2009 at 7:03
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Same problem with identical error message occurring on Vista 32-bit. Version 
1.9.1
```

Original comment by `NiallPLe...@gmail.com` on 20 Jun 2009 at 1:43

**Comment by GoogleCodeExporter** [comment]
```
Only one copy of iTunesMobileDevice.dll  File Version 238.0.0.21 Product 
Version 8.0

No iTunesMobile.dll on the computer.
```

Original comment by `todd...@gmail.com` on 20 Jun 2009 at 4:18

**Comment by GoogleCodeExporter** [comment]
```
http://img151.imageshack.us/img151/3980/image2aya.jpg

iPhoneBrowser 1.9.1
Windows 2003 Datacenter SP2 x32 English
All Windows Updates
.NET 2.0/3.0/3.5

iTunes 8.2
iPhone 3GS 32GB (activated and synchronized)

```

Original comment by `terra...@gmail.com` on 20 Jun 2009 at 4:19

**Comment by GoogleCodeExporter** [comment]
```
todd727 - iPhoneBrowser 1.91 doesn't use AFCGetFileInfo and has no reference to 
it
that I am aware of. Please make sure you are running 1.91 or uninstall and 
reinstall.
Your version of iTunesMobileDevice.dll is internally date stamped older than 
mine,
but mine is 238.0.0.10. In any case, if I put your dll in my iPhoneBrowser 
1.9.1.0
Program Files folder, it works fine (iPhoneBrowser loads a local copy first).

terrabay: iPhoneBrowser won't give you special file system access without a 
jailbreak
for the 3G S but you should see the DCIM and iTunes folders in iPhoneBrowser. 
Can you
search and verify you have the iTunesMobileDevice.dll for 8.2 only on your 
system? Or
try copying it into the iPhoneBrowser Program Files folder. I don't have a copy 
of
Windows 2003 Datacenter for testing :)
```

Original comment by `NetMage....@gmail.com` on 21 Jun 2009 at 7:03

**Comment by GoogleCodeExporter** [comment]
```
NetMage SCW, 

OK, we got it fixed.  Turns out that there were two entries for iPhoneBrowser 
in the
list of installed programs under Control Panel.  Evidently, one of the upgrades
didn't remove the previous version.  Anyway, uninstalled both from CP, cleaned 
the
registry and removed all folders I could find that had any reference to
iPhoneBrowser, including the one under program files and the ones under the
Application Data and Local Settings in the Documents and Settings folder. 
Reinstalled 1.9.1 and all is working again.

So, everyone that is having trouble with 1.9.1 needs to make sure there are no
remnants from a previous version hiding on the computer.

Thanks for working with me to get this resolved.
```

Original comment by `todd...@gmail.com` on 21 Jun 2009 at 2:34

**Comment by GoogleCodeExporter** [comment]
```
BTW, the folder under Documents and Settings|Local Settings|Application Data is 
named
Cranium_Consulting_and_Cu
```

Original comment by `todd...@gmail.com` on 21 Jun 2009 at 2:40

**Comment by GoogleCodeExporter** [comment]
```
Yes, this solved the problem.  I too found two copies of the prog in Control 
Panel. 
Uninstalled both but could not re-install 1.9.1 until I deleted the Cranium 
folder in
Local AppData. Much thanks to NetMage and Todd727.
```

Original comment by `NiallPLe...@gmail.com` on 21 Jun 2009 at 9:51

**Comment by GoogleCodeExporter** [comment]
```
Will test again tomorrow with a HP work PC. My iTunesMobileDevice.dll is 
238.0.0.10.

Cleaed Registry, uninstalled and reinstalled, copyed the DLL into the 
iPhoneBrowser .. all doesn't help. Same error message as previous post.

Let you guys now tomorrow evening.

General question: if this tool doesn't work, how to get your pics out of the 
iPhone ? EMails are shrinked and iTunes has no sync for taken pics ..
```

Original comment by `terra...@gmail.com` on 23 Jun 2009 at 7:13

**Comment by GoogleCodeExporter** [comment]
```
terrabay: Past occurrences of this error generally meant the Apple Mobile 
Device or
iPod services were not running, and re-installing iTunes corrected it.

Does iTunes see the iPhone and allow you to sync music?

For pictures, the iPhone normally appears as a digital camera to Windows (and I
assume the Mac). In Windows, you should see the iPhone in Explorer as a digital
camera, and be able to open the DCIM folder and access the Camera Roll.
```

Original comment by `NetMage....@gmail.com` on 23 Jun 2009 at 11:38

**Comment by GoogleCodeExporter** [comment]
```
terrabay:  Daughter's computer(Vista) was not seeing the iPhone as a camera 
device. 
Ended up going into the hardware tool under control panel and removing the 
iPhone as
a device, rebooted, then hook up the iPhone and let Windows install the correct
driver.  It has worked since them and she has been able to transfer photos off 
of it.
```

Original comment by `todd...@gmail.com` on 24 Jun 2009 at 1:20

**Comment by GoogleCodeExporter** [comment]
```
Good Morning

tested now at work on a clean HP Desktop PC.
Everything works perfectly fine so the problem is with my messy server not 
iPhoneBrowser ;)

Thanks for all the troubleshooting help and this nice tool !

```

Original comment by `terra...@gmail.com` on 24 Jun 2009 at 7:43

**Comment by GoogleCodeExporter** [comment]
```
Same problem here.  iPhone Browser just doesn't support 3.0
```

Original comment by `ChanceMa...@gmail.com` on 27 Jun 2009 at 6:00

**Comment by GoogleCodeExporter** [comment]
```
No, iPhoneBrowser supports 3.0 and the 3G S just fine.  It was a problem with 
the
iPhoneBrowser 1.9 and 1.9.1 upgrade over 1.8.
```

Original comment by `todd...@gmail.com` on 28 Jun 2009 at 2:43

**Comment by GoogleCodeExporter** [comment]
```
browser will start but will not connect to my jail broken 2g phone with 3.0 OS. 
 I 
am rinning on a p3 xp pro sp3.  after I heard about the ituneshelper.dll While 
I was 
using 2.1.2 os and it did work.  but I have not tried that patch again.  I used 
the 
http://easyiphoneunlocking.com updated jailbreak I had some problems with that 
at 
first.  but it turned out that the itunes I was using though it was 8.2 it 
would not 
update the phone to 3.0.  I had to remove and reinstall iTunes and then I was 
able 
to get the 3.0 update.  once I was able to get the 3.0 OS into my 2G phone it 
was 
working.  Though I tried to run the 1.8 and it did not see my phone I removed 
1.8 
and then installed 1.9.  I did it in that order.  though I did not reboot in 
between.

Rescue25
```

Original comment by `escue.bo...@gmail.com` on 10 Jul 2009 at 1:43

**Comment by GoogleCodeExporter** [comment]
```
Upon further testing I notice on this machine it does not see the phone. It 
keeps 
asking for me to ehther to plug in my phone or to disconnet and then to 
reconnect.that is the only other thing I think to mention.  though I tunes sees 
it 
fine.


```

Original comment by `escue.bo...@gmail.com` on 19 Jul 2009 at 9:40

Attachments:
- [1.900 browserscreen shot..gif](https://storage.googleapis.com/google-code-attachments/iphonebrowser/issue-104/comment-16/1.900 browserscreen shot..gif)

**Comment by GoogleCodeExporter** [comment]
```
Ok I figured it out unless I missed it earlier.  I recopied the itunes helper 
version 238.0.0.10 into the iphonebrowser root directory and it worked.
```

Original comment by `escue.bo...@gmail.com` on 20 Jul 2009 at 3:24

**Comment by GoogleCodeExporter** [comment]
```
Hi,

Escue Boone is so right. I only add the remove after I deleted the folder when 
i 
installed afterwards.
```

Original comment by `Helmers...@gmail.com` on 15 Jan 2010 at 8:10
