### ISSUE TITLE
Unhandled exception has occured in your application.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MziRintu/iphonebrowser#121]
```
Hello All,
When I try to backup the root folder of my iphone I receive the following:

Microsoft .NET Framework
Unhandled exception has occured in your application. If you click Continue,
the application will ignore this error and attempt to continue. 
If you click Quit, the application will close immediately.

External component has thrown an exception.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.SEHException: External component has thrown
an exception.
   at Manzana.MobileDevice.AFCFileInfoOpen(Void* conn, String path, Void*&
dict)
   at Manzana.iPhone.Exists(String path)
   at iPhoneBrowser.frmMain.copyFromPhone(String sourceOnPhone, String
destinationOnComputer)
   at iPhoneBrowser.frmMain.backupFileFromPhoneAt(String sSourcePath,
String sSourceFile, DateTime aTime)
   at iPhoneBrowser.frmMain.BackupDirectoryAt(String sPath, DateTime aTime)
   at iPhoneBrowser.frmMain.BackupDirectoryAt(String sPath, DateTime aTime)
   at iPhoneBrowser.frmMain.BackupDirectoryAt(String sPath, DateTime aTime)
   at iPhoneBrowser.frmMain.BackupDirectoryAt(String sPath, DateTime aTime)
   at iPhoneBrowser.frmMain.BackupDirectoryAt(String sPath, DateTime aTime)
   at iPhoneBrowser.frmMain.BackupDirectory(String sPath)
   at iPhoneBrowser.frmMain.BackupFolderToolStripMenuItem_Click(Object
sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e,
ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e,
ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons
button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.42 (RTM.050727-4200)
    CodeBase:
file:///c:/WINDOWS/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
iPhoneBrowser
    Assembly Version: 1.9.1.0
    Win32 Version: 1.9.1.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/iPhoneBrowser.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.50727.42 (RTM.050727-4200)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7f11d5
0a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.42 (RTM.050727-4200)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.42 (RTM.050727-4200)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e
089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.42 (RTM.050727-4200)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/Sy
stem.Drawing.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.42 (RTM.050727-4200)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c5619
34e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.42 (RTM.050727-4200)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50
a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.42 (RTM.050727-4200)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System
.Xml.dll
----------------------------------------
AxInterop.QTOControlLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase:
file:///C:/Program%20Files/iPhoneBrowser/AxInterop.QTOControlLib.DLL
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.42 (RTM.050727-4200)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Acc
essibility.dll
----------------------------------------
Interop.QTOControlLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase:
file:///C:/Program%20Files/iPhoneBrowser/Interop.QTOControlLib.DLL
----------------------------------------
Interop.QTOLibrary
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/Interop.QTOLibrary.DLL
----------------------------------------
Manzana
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/Manzana.DLL
----------------------------------------
ts2bkmvs
    Assembly Version: 2.0.0.0


Win32 Version: 2.0.50727.42 (RTM.050727-4200)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

I have tried different computers and receive the same message. I also tried
backing up seperate folders which I can do but not all of them will backup.
Most of the folders I receive the message above. In addition, I am also
using itunes 8.2 and .net framework 2.0

Any suggestions would be greatly appreciated thanks.

-Thomas

```

Original issue reported on code.google.com by `tmyke...@gmail.com` on 5 Aug 2009 at 6:13

**Comment by GoogleCodeExporter** [comment]
```
Same issue I am facing. It is a show stopper. Bad bug it is without any 
solution when
I google to find out.
```

Original comment by `Murtuza7...@gmail.com` on 8 Aug 2009 at 9:12

**Comment by GoogleCodeExporter** [comment]
```
Yup I agree. I have tried running it on at least three different computers. I 
figured
this was something to do with the IPhone since I had the same issue on each 
computer.
I reformatted and still the same problem.
```

Original comment by `tmyke...@gmail.com` on 25 Aug 2009 at 5:09

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Ups, indentical situation, I doubt to someone help us...maybe...!? If so...
Thanks in advance
```

Original comment by `zoran.ra...@gmail.com` on 4 May 2011 at 1:14

**Comment by GoogleCodeExporter** [comment]
```
Hmmm... Still not fixed. Why is this listed as medium priority, when it is 
clearly a show stopper. Running the latest .net (4) does not help.
```

Original comment by `lscha...@gmail.com` on 30 Jul 2011 at 2:42

**Comment by GoogleCodeExporter** [comment]
```
I have the same. iphone 3G with iTunes 10.4.0.80. Crashes on startup or when 
plug the phone. Can be related to new iTunes?
```

Original comment by `niwas...@gmail.com` on 30 Jul 2011 at 11:59
