### ISSUE TITLE
Crashes when connected to iphone

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MziRintu/iphonebrowser#140]
```
What steps will reproduce the problem?
1. launch iphonebrowser
2. progress bar is working
3. exception

What is the expected output? What do you see instead?
using debugger:
StackTrace: 
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, 
Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at iPhoneBrowser.frmMain.iPhoneConnected_Details()
   at iPhoneBrowser.frmMain.iPhoneConnected_EventHandler(Object sender, 
ConnectEventArgs args)
   at Manzana.iPhone.OnConnect(ConnectEventArgs args)
   at Manzana.iPhone.NotifyCallback(AMDeviceNotificationCallbackInfo& 
callback)
Message:
"Path does not exist"
Source:
"System.Windows.Forms"

What version of the product are you using? On what operating system?
XP SP2, iphone 3g, OS 3.0.1 (7A400). iphonebrowser 1.9.1, itunes 8

Please provide any additional information below.
System.Exception was unhandled
  Message="Path does not exist"
  Source="System.Windows.Forms"
  StackTrace:
       at System.Windows.Forms.Control.MarshaledInvoke(Control caller, 
Delegate method, Object[] args, Boolean synchronous)
       at System.Windows.Forms.Control.Invoke(Delegate method, Object[] 
args)
       at System.Windows.Forms.Control.Invoke(Delegate method)
       at iPhoneBrowser.frmMain.iPhoneConnected_Details()
       at iPhoneBrowser.frmMain.iPhoneConnected_EventHandler(Object 
sender, ConnectEventArgs args)
       at Manzana.iPhone.OnConnect(ConnectEventArgs args)
       at Manzana.iPhone.NotifyCallback(AMDeviceNotificationCallbackInfo& 
callback)
  InnerException: 


```

Original issue reported on code.google.com by `dirty.o....@gmail.com` on 15 Sep 2009 at 4:34

**Comment by GoogleCodeExporter** [comment]
```
Please try v1.93
```

Original comment by `NetMage....@gmail.com` on 21 Sep 2009 at 6:42
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
v1.93 fixes this problem for me
```

Original comment by `WillBarr...@gmail.com` on 21 Sep 2009 at 4:49

**Comment by GoogleCodeExporter** [comment]
```
Re-installing v1.93 worked for me too:
This is what I did:
1.Uninstalled v1.92 using Control Panel
2.Installed v1.93 and worked for me
```

Original comment by `johanma...@gmail.com` on 8 Oct 2009 at 5:07
