### ISSUE TITLE
Preview Not Working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MziRintu/iphonebrowser#17]
```
What steps will reproduce the problem?
1. click on any jpg or txt file in the file browser
2. check the preview area
3.

What is the expected output? What do you see instead?
Expect to see a preview of file - instead, error occurs (see details below
and attachment), click "Continue" in error pop-up, no preview is shown -
this same error occurred on 2 different pc's

What version of the product are you using? On what operating system?
1.5.1.0 Windows XPsp2

Please provide any additional information below.

FYI, there is no directory "Local Settings\Application Data\Cranium" - the
directory there is "Cranium_Consulting_and_Cu" and that has 2 folders, 
1) iPhoneBrowser.exe_Url_2k2ljmnkfhgowhjnczlowzwi0pdhrnrz
2) iPhoneBrowser.exe_Url_mr4ptbwm2xkjc0qqjok3tephqyycuz52

ERROR LOG:

System.IO.DirectoryNotFoundException: Could not find a part of the path
'C:\Documents and Settings\(local usr)\Local Settings\Application
Data\Cranium\iPhoneBrowser\iPhone.temp.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess
access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize,
FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean
bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess
access, FileShare share)
   at iPhoneBrowser.frmMain.copyFromPhone(String sourceOnPhone, String
destinationOnComputer)
   at iPhoneBrowser.frmMain.ShowPreview(String sFile)
   at iPhoneBrowser.frmMain.DoFileSelectedPreview(Boolean anySize)
   at iPhoneBrowser.frmMain.lstFiles_SelectedIndexChanged(Object sender,
EventArgs e)
   at System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
iPhoneBrowser
    Assembly Version: 1.5.1.0
    Win32 Version: 1.5.1.0
    CodeBase: file:///C:/Documents%20and%20Settings/(local
usr)/Desktop/iPhoneBrowser.1.51/iPhoneBrowser.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.50727.42 (RTM.050727-4200)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7f11d5
0a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e
089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/Sy
stem.Drawing.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c5619
34e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50
a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System
.Xml.dll
----------------------------------------
AxInterop.QTOControlLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Documents%20and%20Settings/(local
usr)/Desktop/iPhoneBrowser.1.51/AxInterop.QTOControlLib.DLL
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.42 (RTM.050727-4200)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Acc
essibility.dll
----------------------------------------
Interop.QTOControlLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Documents%20and%20Settings/(local
usr)/Desktop/iPhoneBrowser.1.51/Interop.QTOControlLib.DLL
----------------------------------------
Manzana
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Documents%20and%20Settings/(local
usr)/Desktop/iPhoneBrowser.1.51/Manzana.DLL
----------------------------------------
9c2jol4m
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
SCW_iPhonePNG
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Documents%20and%20Settings/(local
usr)/Desktop/iPhoneBrowser.1.51/SCW_iPhonePNG.DLL
----------------------------------------


```

Original issue reported on code.google.com by `michaeld...@gmail.com` on 9 Jan 2008 at 11:55

Attachments:
- [preview error screenshot_1.9.08.jpg](https://storage.googleapis.com/google-code-attachments/iphonebrowser/issue-17/comment-0/preview error screenshot_1.9.08.jpg)

**Comment by GoogleCodeExporter** [comment]
```
hello i have exactly the same problem (see post 16, but its german)
lets hope theres a solution =)
```

Original comment by `luiz.2...@gmail.com` on 10 Jan 2008 at 9:33

**Comment by GoogleCodeExporter** [comment]
```
Fixed in latest version
```

Original comment by `NetMage....@gmail.com` on 11 Sep 2008 at 6:37
- Changed state: **Fixed**
