### ISSUE TITLE
an unhandled exception ('system.InvalidOperationException?')

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MziRintu/iphonebrowser#227]
```
What steps will reproduce the problem?
1. download product
2. complete installation
3. doubleclick on desktop icon

What is the expected output? What do you see instead?
Expected application to open - instead recieved the error message: 

"an unhandled exception ('system.InvalidOperationException?') occurred in 
iPhoneBrowser.exe 1856?".

What version of the product are you using? On what operating system?
SetupiPhoneBrowser.1.93.exe on XP Professional V2002 - SP3

Please provide any additional information below.

I'm sitting behind a firewall but have complete access to the internet except 
for social media and streaming media sites...

when I go to start the program i get the error "an unhandled exception 
('system.InvalidOperationException?') occurred in iPhoneBrowser.exe 1856?". 

Any ideas as to how i get around this or why this is happening. 




```

Original issue reported on code.google.com by `Brucega...@gmail.com` on 30 Nov 2010 at 11:16

Attachments:
- [iphoneerror1.gif](https://storage.googleapis.com/google-code-attachments/iphonebrowser/issue-227/comment-0/iphoneerror1.gif)
- [iphoneerror2.gif](https://storage.googleapis.com/google-code-attachments/iphonebrowser/issue-227/comment-0/iphoneerror2.gif)

**Comment by GoogleCodeExporter** [comment]
```
I'm t-shooting this issue now.... It seems that the app requires some other 
files.... I'm trying to debug it to find out what. Maybe I can decompile the 
thing/...
Here is some more info about the error:
{"Class not registered (Exception from HRESULT: 0x80040154 
(REGDB_E_CLASSNOTREG))"}
   at iPhoneBrowser.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at iPhoneBrowser.My.MyProject.MyForms.get_frmMain()
   at iPhoneBrowser.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at iPhoneBrowser.My.MyApplication.Main(String[] Args)
```

Original comment by `CrazyLo...@gmail.com` on 24 Dec 2010 at 12:43
