### ISSUE TITLE
Files with size >2GB cause crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MziRintu/iphonebrowser#38]
```
What steps will reproduce the problem?
1. Have a file with size >2GB in a folder (like wiki2touch wikipedia db)
2. Navigate to that folder
3.

What is the expected output? What do you see instead?
Crash happens, see below. Obviously the Manzana.iPhone.GetFileInfo only
handles 32bit sizes. You must either add support for large files or at
least catch the exception and display question marks for size...

What version of the product are you using? On what operating system?
1.5.2.0 on WinXP

Please provide any additional information below.
************** Exception Text **************
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ParseInt32(String s, NumberStyles style,
NumberFormatInfo info)
   at Manzana.iPhone.GetFileInfo(String path, Int32& size, Boolean& directory)
   at Manzana.iPhone.IsDirectory(String path)
   at Manzana.iPhone.GetDirectories(String path)
   at iPhoneBrowser.frmMain.addFolders(String sPath, TreeNode&
selectedNode, Int32 iDepth)
   at iPhoneBrowser.frmMain.trvFolders_KeyUp(Object sender, KeyEventArgs e)
   at System.Windows.Forms.Control.OnKeyUp(KeyEventArgs e)
   at System.Windows.Forms.TreeView.OnKeyUp(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
IntPtr wparam, IntPtr lparam)


```

Original issue reported on code.google.com by `achim.bu...@gmail.com` on 16 May 2008 at 9:24

**Comment by GoogleCodeExporter** [comment]
```
Actually, when first navigating to the folder, it is not even shown in the 
tree. Only
after pressing F5 it is shown and immediately the exception is thrown.
```

Original comment by `achim.bu...@gmail.com` on 16 May 2008 at 9:27

**Comment by GoogleCodeExporter** [comment]
```
Will be in version after 1.8
```

Original comment by `NetMage....@gmail.com` on 11 Sep 2008 at 6:28
- Changed state: **Started**
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
Original comment by `NetMage....@gmail.com` on 11 Sep 2008 at 6:45
- Changed state: **Duplicate**
