### ISSUE TITLE
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MziRintu/iphonebrowser#50]
```
What steps will reproduce the problem?
1. Deleting a file who has more than 260 characters
2.
3.

What is the expected output? What do you see instead?
File should be deleted without exceptions.

What version of the product are you using? On what operating system?
1.7.0.0

Please provide any additional information below.

************** Exception Text **************
System.IO.PathTooLongException: The specified path, file name, or both are
too long. The fully qualified file name must be less than 260 characters,
and the directory name must be less than 248 characters.
   at System.IO.Path.NormalizePathFast(String path, Boolean fullCheck)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess
access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize,
FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean
bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess
access, FileShare share)
   at iPhoneBrowser.frmMain.copyFromPhone(String sourceOnPhone, String
destinationOnComputer)
   at iPhoneBrowser.frmMain.backupFileFromPhoneAt(String sSourcePath,
String sSourceFile, DateTime aTime)
   at iPhoneBrowser.frmMain.BackupDirectoryAt(String sPath, DateTime aTime)
   at iPhoneBrowser.frmMain.BackupDirectoryAt(String sPath, DateTime aTime)
   at iPhoneBrowser.frmMain.BackupDirectoryAt(String sPath, DateTime aTime)
   at iPhoneBrowser.frmMain.BackupDirectoryAt(String sPath, DateTime aTime)
   at iPhoneBrowser.frmMain.BackupDirectoryAt(String sPath, DateTime aTime)
   at iPhoneBrowser.frmMain.BackupDirectory(String sPath)
   at iPhoneBrowser.frmMain.ToolStripMenuItemDeleteFolder_Click(Object
sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e,
ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e,
ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons
button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
iPhoneBrowser
    Assembly Version: 1.7.0.0
    Win32 Version: 1.7.0.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/iPhoneBrowser.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.50727.42 (RTM.050727-4200)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7f11d5
0a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e
089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/Sy
stem.Drawing.dll
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.42 (RTM.050727-4200)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Acc
essibility.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c5619
34e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50
a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System
.Xml.dll
----------------------------------------
AxInterop.QTOControlLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase:
file:///C:/Program%20Files/iPhoneBrowser/AxInterop.QTOControlLib.DLL
----------------------------------------
Interop.QTOControlLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase:
file:///C:/Program%20Files/iPhoneBrowser/Interop.QTOControlLib.DLL
----------------------------------------
Interop.QTOLibrary
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/Interop.QTOLibrary.DLL
----------------------------------------
Manzana
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/Manzana.DLL
----------------------------------------
pn8b115l
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
SCW_iPhonePNG
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/SCW_iPhonePNG.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

Original issue reported on code.google.com by `cal...@gmail.com` on 29 Aug 2008 at 2:22

**Comment by GoogleCodeExporter** [comment]
```
Forgot to add more system details, ran iPhoneBrowser 1.7.0.0 on Windows XP, SP2 
and
my iPhone is 2G (8GB), firmware 1.1.4 and jailbroken with ZiPhone

```

Original comment by `cal...@gmail.com` on 29 Aug 2008 at 2:38

**Comment by GoogleCodeExporter** [comment]
```
You can use Long Path Tool for such problems, it works good.
```

Original comment by `pawanyad...@gmail.com` on 24 Jan 2014 at 10:00
