### ISSUE TITLE
iphonebrowser crashes after iTunes 8.2 Update

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MziRintu/iphonebrowser#87]
```
What steps will reproduce the problem?
1. update iTunes to version 8.2
2. connect iPhone
3.

What is the expected output? What do you see instead?
expect program to not crash.
Windows error messages, see attached.

Unable to find entry point named 'AFCGetFileInfo' in DLL
'iTunesMobileDevice.dll'

What version of the product are you using? On what operating system?
iphonebrowser v1.8.1.0
Windows XP Pro
iTunes 8.2

Please provide any additional information below.

Here are the debugging details:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.EntryPointNotFoundException: Unable to find an entry point named
'AFCGetFileInfo' in DLL 'iTunesMobileDevice.dll'.
   at Manzana.MobileDevice.AFCGetFileInfo(IntPtr conn, String path, IntPtr&
buffer, UInt32& length)
   at Manzana.iPhone.GetFileInfo(String path, UInt64& size, Boolean& directory)
   at Manzana.iPhone.GetFiles(String path)
   at iPhoneBrowser.frmMain.loadFiles()
   at iPhoneBrowser.frmMain.trvFolders_AfterSelect(Object sender,
TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3082 (QFE.050727-3000)
    CodeBase:
file:///c:/WINDOWS/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
iPhoneBrowser
    Assembly Version: 1.8.1.0
    Win32 Version: 1.8.1.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/iPhoneBrowser.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.50727.3053 (netfxsp.050727-3000)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7f11d5
0a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e
089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/Sy
stem.Drawing.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c5619
34e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50
a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3082 (QFE.050727-3000)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System
.Xml.dll
----------------------------------------
AxInterop.QTOControlLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase:
file:///C:/Program%20Files/iPhoneBrowser/AxInterop.QTOControlLib.DLL
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Acc
essibility.dll
----------------------------------------
Interop.QTOControlLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase:
file:///C:/Program%20Files/iPhoneBrowser/Interop.QTOControlLib.DLL
----------------------------------------
Interop.QTOLibrary
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/Interop.QTOLibrary.DLL
----------------------------------------
Manzana
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/Manzana.DLL
----------------------------------------
7oehpsi1
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase:
file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

Original issue reported on code.google.com by `leode...@yahoo.com` on 3 Jun 2009 at 8:15

Attachments:
- [iphonebrowser_error01.jpg](https://storage.googleapis.com/google-code-attachments/iphonebrowser/issue-87/comment-0/iphonebrowser_error01.jpg)
- [iphonebrowser_error02.jpg](https://storage.googleapis.com/google-code-attachments/iphonebrowser/issue-87/comment-0/iphonebrowser_error02.jpg)

**Comment by GoogleCodeExporter** [comment]
```
is there any way to fix this? or any way to return to the previous itunes?
```

Original comment by `AlDen...@gmail.com` on 3 Jun 2009 at 9:23

**Comment by GoogleCodeExporter** [comment]
```
the application will need to be updated, since iTunes 8.2 is REQUIRED for 
upgrading
to iPhone OS 3.0  

Of course jailbreak hacks will need to be updated too so they work with OS 3.0
```

Original comment by `leode...@yahoo.com` on 3 Jun 2009 at 9:26

**Comment by GoogleCodeExporter** [comment]
```
Confirm that with 8.2 this one crashes :( 
```

Original comment by `terra...@gmail.com` on 4 Jun 2009 at 8:32

**Comment by GoogleCodeExporter** [comment]
```
same issue, will try on different box and be back again.
```

Original comment by `peter.th...@gmail.com` on 6 Jun 2009 at 11:27

**Comment by GoogleCodeExporter** [comment]
```
I got it working by replacing 'iTunesMobileDevice.dll' witha older version
```

Original comment by `boadicea...@hotmail.com` on 7 Jun 2009 at 1:47

**Comment by GoogleCodeExporter** [comment]
```
Cant find iTunesMobileDevice.dll in iPhoneBrowser folder. Where to change the 
file and 
How to get the old version ?
```

Original comment by `rahnas` on 7 Jun 2009 at 3:06

**Comment by GoogleCodeExporter** [comment]
```
If you google iTunesMobileDevice.dll you will find a copy then replace the copy 
at 
C:\Program Files\Common Files\Apple\Mobile Device Support\bin 
```

Original comment by `boadicea...@hotmail.com` on 7 Jun 2009 at 4:33

**Comment by GoogleCodeExporter** [comment]
```
Worked perfectly, thanks!
```

Original comment by `leode...@yahoo.com` on 9 Jun 2009 at 9:34

**Comment by GoogleCodeExporter** [comment]
```
replacing itunesmobiledecice.dll cause me a little trouble with some apps, they 
crash 
every time i "clic" on them, i fix it by returning the original 
itunesmobiledecice.dll 
to its place, besides that iphonebrowser worked perfectly
```

Original comment by `AlDen...@gmail.com` on 9 Jun 2009 at 10:21

**Comment by GoogleCodeExporter** [comment]
```
iPhoneBrowser checks for iTunesMobileDevice.dll in its own installation folder 
first. 
So just copy the old dll there.

Here is the first occurrence of the DLL in the startup profile of 
iPhoneBrowser.exe:

LoadLibraryExW("d:\program files\iphonebrowser\iTunesMobileDevice.dll", 
0x00000000, 
LOAD_WITH_ALTERED_SEARCH_PATH) called from "MSCORWKS.DLL" at address 0x79F4CE65.
```

Original comment by `lolly....@gmail.com` on 9 Jun 2009 at 11:50

**Comment by GoogleCodeExporter** [comment]
```
v1.90 now works with iTunes 8.2 (not sure about previous versions)
```

Original comment by `NetMage....@gmail.com` on 12 Jun 2009 at 7:49
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
the following strategy worked: google iTunesMobileDevice.dll, select the first 
search result and download the iTunesMobileDevice.dll file. copy this file in 
the 
iphonebrowser folder. worked perfectly...windows xp home edition, iphone 
browser 
version 1.4.0.0 
```

Original comment by `vendadth...@gmail.com` on 20 Aug 2009 at 10:50

**Comment by GoogleCodeExporter** [comment]
```
How to read other information such as

     * ActivationState
     * ActivationStateAcknowledged
     * BasebandBootloaderVersion
     * BasebandVersion
     * BluetoothAddress
     * BuildVersion
     * DeviceCertificate
     * DeviceClass
     * DeviceName
     * DevicePublicKey
     * FirmwareVersion
     * HostAttached
     * IntegratedCircuitCardIdentity
     * InternationalMobileEquipmentIdentity
     * InternationalMobileSubscriberIdentity
     * ModelNumber
     * PhoneNumber
     * ProductType
     * ProductVersion
     * ProtocolVersion
     * RegionInfo
     * SBLockdownEverRegisteredKey
     * SIMStatus
     * SerialNumber
     * SomebodySetTimeZone
     * TimeIntervalSince1970
     * TimeZone
     * TimeZoneOffsetFromUTC
     * TrustedHostAttached
     * UniqueDeviceID
     * Uses24HourClock
     * WiFiAddress
     * iTunesHasConnected

```

Original comment by `Gnanavad...@gmail.com` on 17 Mar 2011 at 6:47
