### ISSUE TITLE
iPhonebrowser crashes when I plug in my iPhone, but is otherwise completely stable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MziRintu/iphonebrowser#94]
```
What steps will reproduce the problem?
1. Start iphonebrowser
2. Plug in my iPhone
3.

Alternatively
1. Plug in my iPhone
2. Start the iphonebrowser

What is the expected output? What do you see instead?
I expect to be able to view the files on my iPhone, however the program
crashes bringing up the Windows error report window.

What version of the product are you using? On what operating system?
I am using v1.9.0.0 on Windows XP. My iPhone has been jailbroken with the
latest version of Quickpwn, and my iTunes is version 8.2.

Please provide any additional information below.
I have tried using an older version of the iTunesmobiledevice.dll, but this
did not solve the problem.

```

Original issue reported on code.google.com by `Hella...@gmail.com` on 13 Jun 2009 at 8:37

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem, every time when I plug in my iPhone the iPhonebrowser 
crashes. Before just a few days worked great, but now crashes and I don't know 
what 
is the reason for that. I'm using iPhonebrowser v1.9 on Windows Vista 32bit and 
iTunes v8.2. I've tried to reinstall the iPhonebrowser, iTunesMobileDevice.dll 
too 
and system restore but doesn't help... 
```

Original comment by `didosdes...@gmail.com` on 16 Jun 2009 at 11:35

Attachments:
- [iPB_shot.jpg](https://storage.googleapis.com/google-code-attachments/iphonebrowser/issue-94/comment-1/iPB_shot.jpg)

**Comment by GoogleCodeExporter** [comment]
```
1 more for the same issue!
```

Original comment by `hardi...@gmail.com` on 17 Jun 2009 at 2:39

**Comment by GoogleCodeExporter** [comment]
```
It's the same problem on my Computer. Could it be, that it's because of the new
iTunes version????
```

Original comment by `heldenba...@gmail.com` on 17 Jun 2009 at 8:18

**Comment by GoogleCodeExporter** [comment]
```
New iTunes or not, I've never had this program working. I've tried older 
versions of both programs on a 
completely separate computer and could not get it to do anything but crash upon 
connecting the iPhone
```

Original comment by `wrjpow...@gmail.com` on 17 Jun 2009 at 11:59

**Comment by GoogleCodeExporter** [comment]
```
The interesting thing is that, the same iPhone with the same version of the 
iPhonebrowser downloaded from the same place but the iPhone pluged in on 
another PC 
working great, when i try to plug in on my PC just crashes and bringing up the 
windows error window... Please give us any solution of this problem, or let us 
know 
the reason for that crash, I really need iPhonebrowser. 

BTW: I've tried to install a similar software to iPhonebrowser called 
iPhoneList and 
I had absolutely the same problem when I pluged the iPhone to PC... That's why 
I was 
thinkink the problem comes from my iPhone, but when I tried with other PC works 
great, so I think the problen is not in my iPhone...
```

Original comment by `didosdes...@gmail.com` on 17 Jun 2009 at 3:05

**Comment by GoogleCodeExporter** [comment]
```
Please try v1.91 - this version works with Windows 7 and hopefully Vista
```

Original comment by `NetMage....@gmail.com` on 18 Jun 2009 at 6:11
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
NetMage.SCW,thanks a lot for your reply... the iPhonebrowser v1.91 works great 
on 
Vista!!! Many Thanks!
```

Original comment by `didosdes...@gmail.com` on 18 Jun 2009 at 9:46

**Comment by GoogleCodeExporter** [comment]
```
and be sure to download .net framework 3.5
```

Original comment by `omarv...@gmail.com` on 5 Aug 2009 at 9:30

**Comment by GoogleCodeExporter** [comment]
```
Same issue on vista running iPB 1.91 with itunes 9
```

Original comment by `thomaske...@gmail.com` on 14 Sep 2009 at 11:58

**Comment by GoogleCodeExporter** [comment]
```
same issue on ipod touch 2G firmware 3.0 vista 32 bits itunes 9
```

Original comment by `yan.ver...@gmail.com` on 14 Sep 2009 at 5:38

**Comment by GoogleCodeExporter** [comment]
```
Super same issue.... xp and v1.91.  Noticed this after the latest itunes 
version 9
was installed, and I believe the driver for the iphone to windows was updated 
as part
of it.
```

Original comment by `chris.bo...@gmail.com` on 15 Sep 2009 at 7:55

**Comment by GoogleCodeExporter** [comment]
```
I am afaraid I ave the same issue on a fresh machine fully patched with Vista. I
tried a competitors iphone browser and same issue again which leads me to 
thinks its
not the application, perhaps either windows (latest patches) or iTunes.
```

Original comment by `MonirMoh...@gmail.com` on 15 Sep 2009 at 8:08

**Comment by GoogleCodeExporter** [comment]
```
I have the same issue, I tired reinstalling all framework version, I tired 
Itune 8 
and 9, i tried to jailbrake the phone and try and I also tried to run in with 
out 
being jailbroken, it does the same thing, it just crashes.

Below are the errors i collected that may help.

EventType : clr20r3     P1 : iphonebrowser.exe     P2 : 1.9.1.0     
P3 : 4a39d606     P4 : system.windows.forms     P5 : 2.0.0.0     P6 : 4889dee7
P7 : 1521     P8 : 12f     P9 : system.exception, 



See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Path does not exist
   at Manzana.iPhone.GetFiles(String path)
   at iPhoneBrowser.frmMain.loadFiles()
   at iPhoneBrowser.frmMain.trvFolders_AfterSelect(Object sender, TreeViewEventArgs 
e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr 
wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3082 (QFE.050727-3000)
    CodeBase: file:///C:/WINDOWS/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
iPhoneBrowser
    Assembly Version: 1.9.1.0
    Win32 Version: 1.9.1.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/iPhoneBrowser.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7f11d5
0a3a/
Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e
089/S
ystem.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/Sy
stem.
Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50
a3a/S
ystem.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3082 (QFE.050727-3000)
    CodeBase: 
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System
.Xml.
dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/WINDOWS/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c5619
34e08
9/System.Runtime.Remoting.dll
----------------------------------------
AxInterop.QTOControlLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/AxInterop.QTOControlLib.DLL
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/WINDOWS/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Acc
essib
ility.dll
----------------------------------------
Interop.QTOControlLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/Interop.QTOControlLib.DLL
----------------------------------------
Interop.QTOLibrary
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/Interop.QTOLibrary.DLL
----------------------------------------
Manzana
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files/iPhoneBrowser/Manzana.DLL
----------------------------------------
xiov0zbf
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
    CodeBase: 
file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

Original comment by `cyberma...@gmail.com` on 21 Sep 2009 at 3:04

**Comment by GoogleCodeExporter** [comment]
```
@cyberma007

Before iTunes update, I had no problems with iPhonebrowser, but
after update iTunes to 9 the iPhonebrowser crashes.

I tried with the last beta version of iPhonebrowser 1.93 (uploaded 
today) and now everything works just great!

Try with this, and I think will works for you too...
```

Original comment by `didosdes...@gmail.com` on 21 Sep 2009 at 3:21

**Comment by GoogleCodeExporter** [comment]
```
same problem
```

Original comment by `aaron.de...@gmail.com` on 21 Oct 2009 at 10:01

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
v1.93 (Beta) works for now. At least it doesn't crash upon startup.
```

Original comment by `kgy...@gmail.com` on 26 Oct 2009 at 2:00

**Comment by GoogleCodeExporter** [comment]
```
yep, i can confirm that 1.93 (beta) has fixed this problem for me
```

Original comment by `nix1...@gmail.com` on 9 Nov 2009 at 1:47

**Comment by GoogleCodeExporter** [comment]
```
I can confirm too 1.93 beta solved the problem
```

Original comment by `Jede...@gmail.com` on 15 Nov 2009 at 1:06

**Comment by GoogleCodeExporter** [comment]
```
1.93 beta fixed this issue for me as well.
```

Original comment by `UmbralEc...@gmail.com` on 26 Dec 2009 at 11:44

**Comment by GoogleCodeExporter** [comment]
```
v1.91 was crashing on Windows 7 64 bit.

v1.93 beta is no longer crashing.
```

Original comment by `russell....@gmail.com` on 12 Jan 2010 at 7:49

**Comment by GoogleCodeExporter** [comment]
```
Hey guys! I want to confirm it too.

Installing v1.93 Beta fixed the problem for me :D
```

Original comment by `ase...@gmail.com` on 20 Jan 2010 at 11:02

**Comment by GoogleCodeExporter** [comment]
```
Hi all,

I have an iPhone 3G on 3.1.2 with Blackra1n, and I confirm that v1.93 works 
perfectly 
with Windows 7 Pro x86.

Cheers,

Iain
```

Original comment by `c.n.t...@gmail.com` on 28 Feb 2010 at 11:33

**Comment by GoogleCodeExporter** [comment]
```
Hiiii I alos had same problem with windows 7  but it got solved with 1.93 beta 
version.
```

Original comment by `himansh...@gmail.com` on 24 Mar 2010 at 7:26

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
problem solved for iphone browser crash on startup:

Be aware you have the following installed before installing ans starting an 
Iphonebrowser product:

Itunes
.Net Framework

And last but not least: Quicktime.

DON NOT FORGET TO START ITUNES AND QUICKTIME AT LEAST ONCE BEFORE STARTING 
IPHONE BROWSER OR ANY OTHER IPHONE BROWSER PROGRAM.

Greetings from the Netherlands,
MESA

Feel free to send an email if it worked out for you.
```

Original comment by `marckroe...@gmail.com` on 25 Jan 2012 at 1:36
